ttt/src/main/java/com/kf/ttt/controller/NumController.java
ttt/src/main/java/com/kf/ttt/service/NumService.java
ttt/src/main/java/com/kf/ttt/service/NumServiceImpl.java

spring 형태로 파일 수정 중

---

ttt/src/main/java/com/kf/ttt/controller/NumController.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter.java
ttt/src/main/java/com/kf/ttt/service/NumService.java
ttt/src/main/java/com/kf/ttt/service/NumServiceImpl.java

[0915] spring 형태로 변환 중

---

ttt/src/main/java/com/kf/ttt/WebMvcConfig.java
ttt/src/main/java/com/kf/ttt/controller/LoginController.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/controller/UserController.java
ttt/src/main/java/com/kf/ttt/repository/LoginRepository.java
ttt/src/main/java/com/kf/ttt/service/LoginService.java
ttt/src/main/java/com/kf/ttt/service/TransService.java

로그인 기능 구현 중

---

ttt/src/main/java/com/kf/ttt/WebMvcConfig.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/entity/User.java
ttt/src/main/java/com/kf/ttt/service/TransService.java
ttt/src/main/resources/application.properties
ttt/src/main/resources/mybatis/mappers/user.xml

engtokorean java 변환 완료

---

ttt/src/main/java/com/kf/ttt/controller/NumController.java
ttt/src/main/java/com/kf/ttt/entity/Num.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter.java
ttt/src/main/java/com/kf/ttt/repository/NumRepository.java
ttt/src/main/java/com/kf/ttt/service/NumService.java
ttt/src/main/java/com/kf/ttt/test.jsp
ttt/src/main/resources/application.properties
ttt/src/main/resources/mybatis/mappers/num.xml

spring 변환 중, db 연동

---

ttt/src/main/java/com/kf/ttt/controller/AdminController.java
ttt/src/main/java/com/kf/ttt/controller/LoginController.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/entity/User.java
ttt/src/main/java/com/kf/ttt/repository/UserRepository.java
ttt/src/main/java/com/kf/ttt/service/TransService.java
ttt/src/main/java/com/kf/ttt/service/UserService.java
ttt/src/main/resources/mybatis/mappers/user.xml

로그인 구현 완료
관리자 로그인 시 회원목록 조회 완료
관리자 로그인 시 회원추가 완료
eng To Korean 기능
텍스트 -> 문장 수정 완료
조사분리 기능 수정 중

0921_ 기능 구현

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter2.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java
ttt/src/main/resources/application.properties

문장에서 숫자만 찾아서 이중전사하는 기능 구현 완료
전화번호 이중전사 기능 수정 중

0922 숫자 이중전사

---

ttt/src/main/java/com/kf/ttt/controller/AdminController.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/entity/TransLog.java
ttt/src/main/java/com/kf/ttt/repository/TransLogRepository.java
ttt/src/main/java/com/kf/ttt/repository/UserRepository.java
ttt/src/main/java/com/kf/ttt/service/TransLogService.java
ttt/src/main/java/com/kf/ttt/service/TransService.java
ttt/src/main/java/com/kf/ttt/service/UserService.java
ttt/src/main/resources/mybatis/mappers/transLog.xml
ttt/src/main/resources/mybatis/mappers/user.xml

전사 기록 db log 테이블에 저장 기능 구현 중
engToKorean  전사시 조사 분리 구현 중

전사 기록 db log 테이블에 저장 기능 구현 중

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter2.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

다른 숫자 변환 프로그램과 유기적으로 연결되도록 수정 중

0925 전화번호 이중전사 기능 수정 중

---

ttt/src/main/java/com/kf/ttt/controller/LoginController.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/entity/User.java
ttt/src/main/java/com/kf/ttt/service/UserService.java
ttt/src/main/resources/mybatis/mappers/transLog.xml
ttt/src/main/resources/mybatis/mappers/user.xml

DTO 파일 추가 고민 중
전사 log history 조회 구현 중
engToKorean 조사 분리 구현 중

log db 저장 구현 완료

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

0926 전화번호 전사 수정 완료

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter2.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

한 문장에 숫자 2개 인식되지 않는 문제 해결
'년, 월, 일, 시' 전사 작업 중

한 문장에 숫자 2개 인식되지 않는 문제 해결

---

ttt/src/main/java/com/kf/ttt/controller/AdminController.java
ttt/src/main/java/com/kf/ttt/controller/BoardController.java
ttt/src/main/java/com/kf/ttt/controller/LoginController.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/entity/Board.java
ttt/src/main/java/com/kf/ttt/repository/BoardRepository.java
ttt/src/main/java/com/kf/ttt/repository/TransLogRepository.java
ttt/src/main/java/com/kf/ttt/service/BoardService.java
ttt/src/main/java/com/kf/ttt/service/TransLogService.java
ttt/src/main/resources/mybatis/mappers/board.xml
ttt/src/main/resources/mybatis/mappers/transLog.xml

공지사항 게시판 조회 구현 완료
engtokorean 조사 분리 구현중

log history 조회 구현 완료

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

소수 이중전사 기능 구현 중
기념일과의 구분은 추후 구현 예정

소수 이중전사 기능 구현 중

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

전화번호 이중전사 수정 완료 (띄어쓰기, 하이픈 인식 가능)
소수 입력 시 '10.5 -> 일공 점 오'로 출력되는 오류 수정 중

전화번호 수정 완료 및 소수 오류 수정 중

---

ttt/src/main/java/com/kf/ttt/controller/AdminController.java
ttt/src/main/java/com/kf/ttt/controller/BoardController.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/repository/BoardRepository.java
ttt/src/main/java/com/kf/ttt/service/BoardService.java
ttt/src/main/resources/mybatis/mappers/board.xml

특수기호 전사 구현중
engToKorean 조사분리 구현중

공지사항 상세보기 구현 완료

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter2.java
ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

소수 이중전사 기능 수정 및 구현 완료
기념일 이중전사 기능 추가 예정

소수 전사 오류 수정 완료

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

소수와 기념일 구분하여 전사하는 기능 구현 완료
단위 (km, cm, mm 등) 전사하는 기능 구현 중

기념일 전사 완료 및 단위 전사 기능 구현 중

---

ttt/src/main/java/com/kf/ttt/controller/BoardController.java
ttt/src/main/java/com/kf/ttt/controller/LogoutController.java
ttt/src/main/java/com/kf/ttt/repository/BoardRepository.java
ttt/src/main/java/com/kf/ttt/service/BoardService.java
ttt/src/main/resources/mybatis/mappers/board.xml

공지사항 게시판 새글 등록 구현 완료

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

* 측정 단위 전사 기능 구현 완료
* 한 문장에 하나의 숫자만 전사되는 오류 수정 중

단위 전사 기능 구현 완료

---

ttt/src/main/java/com/kf/ttt/controller/AdminController.java
ttt/src/main/java/com/kf/ttt/controller/TransController.java
ttt/src/main/java/com/kf/ttt/repository/TransLogRepository.java
ttt/src/main/java/com/kf/ttt/service/TransLogService.java
ttt/src/main/resources/mybatis/mappers/transLog.xml

검색 조회 건수가 많을 경우 성능이 저하되는 건 수정 중

전사기록 검색 기능 구현 중

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

* 한 문장에 2개 이상의 숫자 이중전사 기능 구현 완료
* 소수와 일반수 함께 전사하는 기능 구현 중

한 문장에 2개 이상의 숫자 이중전사 기능 구현 완료

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

* 한 문장에 소수와 일반수 함께 전사하는 기능 구현 중
* 한 문장에 두 개의 소수 전사하는 기능 구현 중

소수와 일반수, 한 문장에 두 개의 소수 전사 기능 구현 중

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

소수와 자연수 함께 전사하는 기능 구현 중

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

날짜 출력 방식 변경 중

---

ttt/src/main/java/com/kf/ttt/num_kor/NumberConverter3.java

날짜 출력 오류 수정 중
